# Generated by Django 3.0.8 on 2022-05-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
